package com.github.xandergos.terraindiffusionmc.pipeline;

import java.util.List;

/** Stable Terrain Diffusion IDs. They are deliberately independent of registry ordinals. */
public final class BiomeIds {
    private BiomeIds() {}

    public static final short PLAINS=1, SUNFLOWER_PLAINS=2, SNOWY_PLAINS=3, ICE_SPIKES=4,
            DESERT=5, SWAMP=6, MANGROVE_SWAMP=7, FOREST=8, FLOWER_FOREST=9,
            BIRCH_FOREST=10, DARK_FOREST=11, PALE_GARDEN=12, OLD_GROWTH_BIRCH_FOREST=13,
            OLD_GROWTH_PINE_TAIGA=14,
            TAIGA=15, SNOWY_TAIGA=16, SAVANNA=17, SAVANNA_PLATEAU=18,
            WINDSWEPT_HILLS=19, WINDSWEPT_GRAVELLY_HILLS=20, WINDSWEPT_FOREST=21,
            WINDSWEPT_SAVANNA=22, JUNGLE=23, SPARSE_JUNGLE=24, BAMBOO_JUNGLE=25,
            BADLANDS=26, ERODED_BADLANDS=27, WOODED_BADLANDS=28, MEADOW=29,
            CHERRY_GROVE=30, GROVE=31, SNOWY_SLOPES=32, FROZEN_PEAKS=33,
            JAGGED_PEAKS=34, STONY_PEAKS=35, RIVER=36, FROZEN_RIVER=37,
            BEACH=38, SNOWY_BEACH=39, STONY_SHORE=40, WARM_OCEAN=41,
            LUKEWARM_OCEAN=42, DEEP_LUKEWARM_OCEAN=43, OCEAN=44, DEEP_OCEAN=45,
            COLD_OCEAN=46, DEEP_COLD_OCEAN=47, FROZEN_OCEAN=48,
            DEEP_FROZEN_OCEAN=49, MUSHROOM_FIELDS=50, OLD_GROWTH_SPRUCE_TAIGA=51,
            FOREST_SPARSE=108, TAIGA_SPARSE=115, SNOWY_TAIGA_SPARSE=116;

    /** All 51 vanilla surface and ocean biomes (cave-only biomes excluded). */
    public static final List<Short> VANILLA_SURFACE = List.of(
            PLAINS,SUNFLOWER_PLAINS,SNOWY_PLAINS,ICE_SPIKES,DESERT,SWAMP,MANGROVE_SWAMP,
            FOREST,FLOWER_FOREST,BIRCH_FOREST,DARK_FOREST,PALE_GARDEN,
            OLD_GROWTH_BIRCH_FOREST,OLD_GROWTH_PINE_TAIGA,OLD_GROWTH_SPRUCE_TAIGA,
            TAIGA,SNOWY_TAIGA,SAVANNA,SAVANNA_PLATEAU,
            WINDSWEPT_HILLS,WINDSWEPT_GRAVELLY_HILLS,WINDSWEPT_FOREST,WINDSWEPT_SAVANNA,
            JUNGLE,SPARSE_JUNGLE,BAMBOO_JUNGLE,BADLANDS,ERODED_BADLANDS,WOODED_BADLANDS,
            MEADOW,CHERRY_GROVE,GROVE,SNOWY_SLOPES,FROZEN_PEAKS,JAGGED_PEAKS,STONY_PEAKS,
            RIVER,FROZEN_RIVER,BEACH,SNOWY_BEACH,STONY_SHORE,WARM_OCEAN,LUKEWARM_OCEAN,
            DEEP_LUKEWARM_OCEAN,OCEAN,DEEP_OCEAN,COLD_OCEAN,DEEP_COLD_OCEAN,
            FROZEN_OCEAN,DEEP_FROZEN_OCEAN,MUSHROOM_FIELDS);

    public static boolean isOcean(short id) { return id>=WARM_OCEAN && id<=DEEP_FROZEN_OCEAN; }
    public static boolean isShore(short id) { return id==BEACH||id==SNOWY_BEACH||id==STONY_SHORE; }
}
